name: ci

on: push

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14' ]
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GITHUB_BRANCH: ${{ github.ref }}
      BUILD_TARGETS: "darwin/amd64 darwin/386 linux/amd64 linux/386 windows/amd64 windows/386"
      BUILD_NAME: "gdrive"

    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Set enviroment for github-release
        run: |

          if [[ $GITHUB_REF == *tags* ]]; then
            export TAG_NAME="${GITHUB_REF/refs\/tags\//}"
          else 
            export TAG_NAME=""
          fi
          
          echo ::set-env name=RELEASE_TAG::"${TAG_NAME}"
          echo ::set-env name=RELEASE_NAME::"${TAG_NAME}"

          export RELEASE_NOTES="$(git log $(git describe --tags --abbrev=0 --always)..HEAD --pretty=format:"%h - %s (%an)<br>")"
          echo ::set-env name=RELEASE_NOTES::"${RELEASE_NOTES}"
      - name: Build
        run: |
          targets=${BUILD_TARGETS}
          go get -v -u github.com/${GITHUB_REPOSITORY}
          for target in $targets; do
            os="$(echo $target | cut -d '/' -f1)"
            arch="$(echo $target | cut -d '/' -f2)"
            output="build/${BUILD_NAME}_${os}_${arch}"

            echo "-> Building project for: $target"
            GOOS=$os GOARCH=$arch CGO_ENABLED=0 go build -o $output
            #zip -j $output.zip $output > /dev/null
          done
          export RELEASE_FILES=$(echo `ls build/gdrive*`)
          echo $RELEASE_FILES
          echo ::set-env name=RELEASE_FILES::"${RELEASE_FILES}"
      - name: Release
        if: env.RELEASE_TAG != ''
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          body: ${{ env.RELEASE_NOTES }}
          gzip: false
          files: ${{ env.RELEASE_FILES }}
          allow_override: true
  
