name: ci

on: push

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14' ]
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GITHUB_BRANCH: ${{ github.ref }}
      BUILD_TARGETS: "darwin/amd64 darwin/386 linux/amd64 linux/386 windows/amd64 windows/386"
      BUILD_NAME: "gdrive"

    steps:
      - uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Set enviroment for github-release
        run: |
          echo ::set-env name=RELEASE_TAG::"${GITHUB_REF/refs\/tags\//}"
          echo ::set-env name=RELEASE_NAME::"${GITHUB_REF/refs\/tags\//}"
          export RELEASE_NOTES="$(git log $(git describe --tags --abbrev=0 --always)..HEAD --pretty=format:"%h - %s (%an)<br>")"
          echo ::set-env name=RELEASE_NOTES::"${RELEASE_NOTES}"
      - name: Build
        run: |
          targets=${BUILD_TARGETS}
          for target in $targets; do
            os="$(echo $target | cut -d '/' -f1)"
            arch="$(echo $target | cut -d '/' -f2)"
            output="build/${BUILD_NAME}_${os}_${arch}"

            echo "-> Building project for: $target"
            GOOS=$os GOARCH=$arch CGO_ENABLED=0 go build -o $output
          done
      - uses: meeDamian/github-release@1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          body: ${{ env.RELEASE_NOTES }}
          files: build/
          allow_override: true
  
